### ISSUE TITLE
[BUG]: Automate frequent updates via service call without breaking running integration - fails

### ISSUE THREAD

**Issue by kender65** [vingerha/gtfs2#103]
**Thank you**
First of all, I would like to thank you for all your work on this project.

**Describe the solution you'd like**
I want to automate the update of static data every other week or every 4 weeks.

**Describe alternatives you've considered**
I discovered during a manual download and subsequent extraction the integration doesn't work at all but produces many, many, many and many more entries in the log.
I tried the service call in an automation with a smaller file on my test instance and saw the same behavior.

The only way to avoid tons of log entries seems to stop every instance (for each line) of the integration and restart them after the extraction.

**Additional context**
GTFS.DE provides weekly generated static data in their free plan. The content is valid for the next 30 days.
After that sensors set up for different lines (Bus, Train) become unavailable. 
The full dataset for Germany (https://download.gtfs.de/germany/free/latest.zip) is about 220 MB.
Extraction for this file takes 4 to 5 hours (RPi 4B, 8 GB RAM, 256 GB SSD), so slightly ;-) more than documented in the Wiki.
(BTW: this didn't work on my test instance on RPi 4B, 4 GB RAM, 64 GB SD)

An update every other week or every 4 weeks should provide usable data.

So, it would be nice to stop / disable the integration (completely or individually for each instance) as part of the process automatically before the download starts to avoid flooding the log and restart the integration automatically right after the extraction is finished or at least pause the polling of the integration during update process and restart it again.

An automation with stopping the integration first prior to do the service call is just half of the way. To restart the integration an additional trigger after extraction is finished would be neccessary.

Any way to achieve this?

**Comment by vingerha** [comment]
Hi, thanks for bringing this to my attention but the service call does (or better: DID) work for me for 3 datasources and they are similarly large as yours. Trigger by this issue, I now see that all three have failed this weekend so it is recent and since (I guess?) 2024.9 release. Will need to dig into that and since it now affects me too...more prio :)

**Comment by vingerha** [comment]
It is not that bad as I thought. 1 changed URL since this w/e and for the other 2 I use gtfs pro and their sources are blocked.
Can you check if the links at your sources are working (usetheurl in your browser)

**Comment by vingerha** [comment]
It extracted in 6.5 hours today. In the meantime I found some sources of errors and will do more testing before releasing anything new. The idea is that during extraction of a new source, there should be no error nor update.

**Comment by kender65** [comment]
Thanks for your quick replies and sorry for my late response but I was out of town yesterday and didn't have a chance to answer or to do further testing.

I started an update of the static data from https://download.gtfs.de/germany/free/latest.zip (latest update on their side was 8th Sep 2024, 06:03:44). Both downloads, manual via browser and with service call from your integration were successful. Extraction ist still running.
Prior to that I disabled / deactivated 5 of 6 instances to avoid error messages.
After the download finished and during the extraction I tried to set up a new instance but that was denied as aspected (Cannot use this datasource as still unpacking: Germany). Just one entry in the logs.
During the extraction I restarted one of the diabled instances, sensor for this is displayed as unavaiable which make sense for me. Data was outdated a couple of days ago and update hasn't been finished yet. Got one more message (Cannot update this sensor as still unpacking: Germany) in the logs.
Right now it looks much better as there are just a handful of messages in the logs. I will wait for the updated completed and then check logs again.

**Comment by vingerha** [comment]
This makes no sense to me now unless you picked my new updated 'master' branch fro mthe repo. I have improved the error handling and tested an update via the action/service. The only thing missing is the hanlding of bad links, but that is a bit more tricky.

**Comment by vingerha** [comment]
Fixed with release 0.5.0

**Comment by kender65** [comment]
> This makes no sense to me now unless you picked my new updated 'master' branch fro mthe repo. I have improved the error handling and tested an update via the action/service. The only thing missing is the handling of bad url/links/zip, but that is a bit more tricky.


I agree with you, I didn't update the integration over the weekend.
I have an idea what could be the reason:
What have I done or has happened so far?

1. Installed the integration from repo (Start of August)
2. Downloaded the static sources
3. Configured six instances of the integration (three outbound lines, three inbound lines)
4. Disabled the inbound lines after a couple of days (Why? I don't know...)
5. Static data source expired (automatically)
6. Sensors of active instances became unavailable
7. I deactivated all but one instances, the sensor of the only active instance was still unavailable
8. Downloaded an updated static data source today

I think there weren't any entries in the log because the integration didn't do anything because of the inactive instances or the unavailable sensor. The only entries in the log came from my manual attempts to add another instance during the extraction, which took about 4.5 hours today, nearly the same as in the initial download a month ago.

Before I try your fix I give it a try with the current one on my system but many thanks for your immediate correction.
Unfortunately I have to set up new instances, because the current ones don't work any more; the sensors remain unavailable.
![image](https://github.com/user-attachments/assets/573c3c80-bb38-486e-b790-ad76f50a60bf)

![image](https://github.com/user-attachments/assets/5ef0e774-0b97-4970-9784-1463319058d9)

I tried to reload the configuration, I tried to reconfigure it, I restarted HA, nothing helped.

**Comment by vingerha** [comment]
These errors I cannot trace back easily, one needs to analyse them step by step, also, the old source may have been outdated? From the 3 sources that I use (Netherlands, Zou -France and Swizerland) they all came back when I auto-added a new download. My code fixed some other issue that required a manual reload but never had I to reinstall the trip or location. I am not going to try and reproduce your errors with old code so please use the new one and perform an update of the datasource.
I am neidisch of you 4,5h extract as mine was a whopping 2 h more

**Comment by kender65** [comment]
I updated to 0.5.0, updated static data source and can confirm that both instances came back without manually reloading the integration.
But I still get hundreds of warnings in the log during the extraction:

2024-09-10 14:46:27.016 WARNING (MainThread) [custom_components.gtfs2.gtfs_helper] Cannot use this datasource as still unpacking: Germany
2024-09-10 14:46:27.016 WARNING (MainThread) [custom_components.gtfs2.coordinator] Cannot update this sensor as still unpacking: Germany
2024-09-10 14:46:27.017 WARNING (MainThread) [custom_components.gtfs2.sensor] Extracting datasource
2024-09-10 14:47:12.229 WARNING (MainThread) [custom_components.gtfs2.gtfs_helper] Cannot use this datasource as still unpacking: Germany
2024-09-10 14:47:12.230 WARNING (MainThread) [custom_components.gtfs2.coordinator] Cannot update this sensor as still unpacking: Germany
2024-09-10 14:47:12.231 WARNING (MainThread) [custom_components.gtfs2.sensor] Extracting datasource
2024-09-10 14:47:27.016 WARNING (MainThread) [custom_components.gtfs2.gtfs_helper] Cannot use this datasource as still unpacking: Germany
2024-09-10 14:47:27.017 WARNING (MainThread) [custom_components.gtfs2.coordinator] Cannot update this sensor as still unpacking: Germany
2024-09-10 14:47:27.017 WARNING (MainThread) [custom_components.gtfs2.sensor] Extracting datasource
2024-09-10 14:48:12.230 WARNING (MainThread) [custom_components.gtfs2.gtfs_helper] Cannot use this datasource as still unpacking: Germany
2024-09-10 14:48:12.231 WARNING (MainThread) [custom_components.gtfs2.coordinator] Cannot update this sensor as still unpacking: Germany
2024-09-10 14:48:12.232 WARNING (MainThread) [custom_components.gtfs2.sensor] Extracting datasource
2024-09-10 14:48:27.016 WARNING (MainThread) [custom_components.gtfs2.gtfs_helper] Cannot use this datasource as still unpacking: Germany
2024-09-10 14:48:27.017 WARNING (MainThread) [custom_components.gtfs2.coordinator] Cannot update this sensor as still unpacking: Germany
2024-09-10 14:48:27.018 WARNING (MainThread) [custom_components.gtfs2.sensor] Extracting datasource
2024-09-10 14:49:12.230 WARNING (MainThread) [custom_components.gtfs2.gtfs_helper] Cannot use this datasource as still unpacking: Germany
2024-09-10 14:49:12.231 WARNING (MainThread) [custom_components.gtfs2.coordinator] Cannot update this sensor as still unpacking: Germany
2024-09-10 14:49:12.231 WARNING (MainThread) [custom_components.gtfs2.sensor] Extracting datasource

Warnings are repeated every minute, so I think they come from polling for RT-data for each line. I use the standard function instead of retrieving via service call. The latter would still produce warnings I think, probably less if I chose a lower frequency. May be I try this and as these log entries are just warnings neglect them. It just happens during updating static data every 2 or 4 weeks.

Thanks for all your efforts.

**Comment by vingerha** [comment]
Yeah, there are duplicates too so I will reduce them. 
Current logic is that it will trigger for each connection/sensor and with the frequency that you have configured. So two sensors on 5 min basis over 5 hours will then throw 120 messages, this is still a lot but I have not found a good way around that. I do not want to store that a message was already sent, that is code-nonsens for me. Another alternative is that I reduce them to 'debug' level only, assuming that people know why the sensor is not up-to-date.
I could also add a attribute that states 'extracting: true/false'

Other thoughts/ideas welcome....
